import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import AmplifyProvider from "@/components/AmplifyProvider";
import LogoutButton from "@/components/layout/LogoutButton";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AmplifyProvider>
          <div className="relative min-h-screen">
            <div className="absolute right-4 top-4 z-20">
              <LogoutButton />
            </div>
            {children}
          </div>
        </AmplifyProvider>
      </body>
    </html>
  );
}

